### ISSUE TITLE
Spectators get achievements 

### ISSUE THREAD

**Issue by sticks-stuff** [CuzIm1Tigaaa/Spectator#6]
If I spectate a player with a diamond, I will get the [Diamonds!] which is distracting to other players as it doesn't mean anything. Any way to disable this? Thank you!!

**Comment by CuzIm1Tigaaa** [comment]
I mean, you could disable showing advancements or even disable the advancements itself. https://www.spigotmc.org/threads/how-to-turn-off-advancements.255178/

But I can add a possibility to hide them.

**Comment by sticks-stuff** [comment]
For the use case of my and my friends, advancements are still an important part of the game as it reveals what sorta items people have, and we like that

**Comment by Geckomacabre** [comment]
Its because the spectator account is having everyone’s inventories, chests and echest being mirrored thus if a player is wearing diamond armor the spectator account now has diamond armor, im not entirely sure but i dont believe there is a fix for it unless you remove the ability to see inventories(which shouldn’t be done).

**Comment by CuzIm1Tigaaa** [comment]
There might be a possibility, I'll take a look when I'm back home.

**Comment by CuzIm1Tigaaa** [comment]
I'm afraid that this is not possible with spigot.
But it is possible with paper!
So in the next version this will be possible if you use papermc.

**Comment by sticks-stuff** [comment]
Thank you!
